import { SocialMediaLinks } from '@/components/SocialLinks/SocialLinks';
import Footer from '../components/Footer/Footer';
import Navbar from '../components/Navbar/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <SocialMediaLinks />
        {children}
        <Footer />
      </body>
    </html>
  );
}
